name: CI/CD for the project
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm install
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
