import addUser from "../../controllers/users/addUser.ts";
import deactivateUser from "../../controllers/users/deactivateUser.ts";
import getUser from "../../controllers/users/getUser.ts";
import updateUser from "../../controllers/users/updateUser.ts";
import activateUser from "../../controllers/users/activateUser.ts";
import fetchUsers from "../../controllers/users/fetchUsers.ts";
import getLoggedUser from "../../controllers/users/getLoggedUser.ts";
import resetPassword from "../../controllers/users/resetPassword.ts";
import loginUser from "../../controllers/users/loginUser.ts";
import { Router } from "express";
const userRouter = Router();
userRouter.post("/add", addUser);
userRouter.put("/deactivate/:id", deactivateUser);
userRouter.put("/activate/:id", activateUser);
userRouter.put("/update/:id", updateUser);
userRouter.get("/get/:id", getUser);
userRouter.get("/fetch", fetchUsers);
userRouter.get("/getLoggedUser", getLoggedUser);
userRouter.post("/resetPassword", resetPassword);
userRouter.post("/login", loginUser);

export default userRouter;
